// import '../models/mcq_question.dart';

final List<McqQuestion> mcqList = [
  // ✅ APTITUDE (5)
 McqQuestion(domain: "Aptitude", question: "What is the square root of 144?", options: ["10", "12", "14", "16"], answer: "12"),
McqQuestion(domain: "Aptitude", question: "If 5x = 20, what is x?", options: ["2", "4", "5", "6"], answer: "4"),
McqQuestion(domain: "Aptitude", question: "A train travels 120 km in 2 hours. What is its speed?", options: ["50 km/h", "60 km/h", "70 km/h", "80 km/h"], answer: "60 km/h"),
McqQuestion(domain: "Aptitude", question: "What is 15% of 400?", options: ["45", "50", "55", "60"], answer: "60"),
McqQuestion(domain: "Aptitude", question: "How many sides does a pentagon have?", options: ["4", "5", "6", "8"], answer: "5"),
McqQuestion(domain: "Aptitude", question: "What is the least prime number?", options: ["0", "1", "2", "3"], answer: "2"),
McqQuestion(domain: "Aptitude", question: "What is the next number in the series: 2, 4, 8, 16, ?", options: ["18", "20", "24", "32"], answer: "32"),
McqQuestion(domain: "Aptitude", question: "What is the LCM of 3 and 5?", options: ["8", "15", "10", "30"], answer: "15"),
McqQuestion(domain: "Aptitude", question: "If x + 3 = 7, what is x?", options: ["2", "3", "4", "5"], answer: "4"),
McqQuestion(domain: "Aptitude", question: "What is the value of 3² + 4²?", options: ["25", "12", "16", "18"], answer: "25"),
McqQuestion(domain: "Aptitude", question: "What is 10% of 250?", options: ["20", "25", "30", "35"], answer: "25"),
McqQuestion(domain: "Aptitude", question: "Find the missing term: 3, 6, 9, ?, 15", options: ["10", "11", "12", "13"], answer: "12"),
McqQuestion(domain: "Aptitude", question: "If the area of a square is 49, what is its side?", options: ["5", "6", "7", "8"], answer: "7"),
McqQuestion(domain: "Aptitude", question: "Convert 0.75 to fraction.", options: ["1/2", "3/4", "2/3", "4/5"], answer: "3/4"),
McqQuestion(domain: "Aptitude", question: "Speed = Distance / ?", options: ["Time", "Rate", "Speed", "Mass"], answer: "Time"),
McqQuestion(domain: "Aptitude", question: "Which number is both a square and a cube?", options: ["36", "64", "100", "121"], answer: "64"),
McqQuestion(domain: "Aptitude", question: "What is the cube of 3?", options: ["6", "9", "18", "27"], answer: "27"),
McqQuestion(domain: "Aptitude", question: "Simplify: 6 + 3 × 2", options: ["12", "15", "18", "24"], answer: "12"),
McqQuestion(domain: "Aptitude", question: "A clock shows 3:15. What is the angle between the hands?", options: ["0°", "7.5°", "30°", "45°"], answer: "7.5°"),
McqQuestion(domain: "Aptitude", question: "What is the perimeter of a square with side 5 cm?", options: ["10 cm", "15 cm", "20 cm", "25 cm"], answer: "20 cm"),
McqQuestion(domain: "Aptitude", question: "If A = 2 and B = 3, find A² + B².", options: ["11", "12", "13", "14"], answer: "13"),
McqQuestion(domain: "Aptitude", question: "Find the average of 5, 10, 15, 20.", options: ["10", "12.5", "15", "17.5"], answer: "12.5"),
McqQuestion(domain: "Aptitude", question: "If a car travels at 60 km/h for 3 hours, distance is?", options: ["120 km", "150 km", "180 km", "200 km"], answer: "180 km"),
McqQuestion(domain: "Aptitude", question: "1 kilometer = ? meters", options: ["10", "100", "1000", "10000"], answer: "1000"),
McqQuestion(domain: "Aptitude", question: "What is the square of 15?", options: ["200", "225", "250", "275"], answer: "225"),
McqQuestion(domain: "Aptitude", question: "What comes next: 2, 5, 10, 17, ?", options: ["24", "26", "28", "30"], answer: "26"),
McqQuestion(domain: "Aptitude", question: "Simplify: 81 ÷ 9 + 6", options: ["12", "13", "14", "15"], answer: "15"),
McqQuestion(domain: "Aptitude", question: "If CP = Rs. 80, Profit = 25%, find SP.", options: ["Rs. 90", "Rs. 95", "Rs. 100", "Rs. 105"], answer: "Rs. 100"),
McqQuestion(domain: "Aptitude", question: "How many even numbers between 1 and 10?", options: ["4", "5", "6", "7"], answer: "4"),
McqQuestion(domain: "Aptitude", question: "What is the reciprocal of 4?", options: ["1", "1/4", "4", "2"], answer: "1/4"),
McqQuestion(domain: "Aptitude", question: "If 20% of x is 30, what is x?", options: ["100", "120", "150", "160"], answer: "150"),
McqQuestion(domain: "Aptitude", question: "Which is the largest: 2/3, 3/4, 4/5, 5/6?", options: ["2/3", "3/4", "4/5", "5/6"], answer: "5/6"),
McqQuestion(domain: "Aptitude", question: "What is the sum of first 10 natural numbers?", options: ["45", "50", "55", "60"], answer: "55"),
McqQuestion(domain: "Aptitude", question: "Which is not a multiple of 3: 6, 9, 12, 14?", options: ["6", "9", "12", "14"], answer: "14"),
McqQuestion(domain: "Aptitude", question: "Divide 100 in ratio 2:3", options: ["40 and 60", "50 and 50", "20 and 80", "30 and 70"], answer: "40 and 60"),
McqQuestion(domain: "Aptitude", question: "Convert 150 cm to meters.", options: ["1.5 m", "15 m", "0.15 m", "1500 m"], answer: "1.5 m"),
McqQuestion(domain: "Aptitude", question: "What is 1/2 of 3/4?", options: ["3/4", "3/8", "1/4", "1/2"], answer: "3/8"),
McqQuestion(domain: "Aptitude", question: "Which figure has 3 sides?", options: ["Square", "Triangle", "Pentagon", "Hexagon"], answer: "Triangle"),
McqQuestion(domain: "Aptitude", question: "What is 8 x 7?", options: ["56", "64", "72", "48"], answer: "56"),
McqQuestion(domain: "Aptitude", question: "How many seconds in 1 hour?", options: ["360", "3600", "600", "7200"], answer: "3600"),
McqQuestion(domain: "Aptitude", question: "What is 20% of 150?", options: ["25", "30", "35", "40"], answer: "30"),
McqQuestion(domain: "Aptitude", question: "Solve: 50 ÷ 2 + 5", options: ["25", "30", "35", "40"], answer: "30"),
McqQuestion(domain: "Aptitude", question: "The opposite of profit is?", options: ["Gain", "Loss", "Sell", "Buy"], answer: "Loss"),
McqQuestion(domain: "Aptitude", question: "What is 11²?", options: ["111", "121", "131", "141"], answer: "121"),
McqQuestion(domain: "Aptitude", question: "If area = length × breadth, find area of 4×6", options: ["20", "22", "24", "28"], answer: "24"),
McqQuestion(domain: "Aptitude", question: "What is 3/5 as a percentage?", options: ["30%", "50%", "60%", "75%"], answer: "60%"),

  // 👨‍💻 CODING (5)
  McqQuestion(domain: "Coding", question: "What does OOP stand for?", options: ["Object-Oriented Programming", "Open Online Platform", "Operation Over Protocol", "Only Object Parameters"], answer: "Object-Oriented Programming"),
McqQuestion(domain: "Coding", question: "Which of the following is not a programming language?", options: ["Python", "HTML", "Java", "C++"], answer: "HTML"),
McqQuestion(domain: "Coding", question: "Which keyword is used to create a class in Java?", options: ["object", "new", "class", "define"], answer: "class"),
McqQuestion(domain: "Coding", question: "Which data structure is used for DFS?", options: ["Queue", "Stack", "Heap", "Tree"], answer: "Stack"),
McqQuestion(domain: "Coding", question: "Which of these is a dynamically typed language?", options: ["C", "Java", "Python", "C++"], answer: "Python"),
McqQuestion(domain: "Coding", question: "Which operator is used to access members of a class in C++?", options: [".", "::", ":", "#"], answer: "."),
McqQuestion(domain: "Coding", question: "Which data structure uses LIFO?", options: ["Queue", "Array", "Stack", "Linked List"], answer: "Stack"),
McqQuestion(domain: "Coding", question: "Which of the following is not a primitive type in Java?", options: ["int", "char", "boolean", "String"], answer: "String"),
McqQuestion(domain: "Coding", question: "What is the time complexity of Binary Search?", options: ["O(n)", "O(log n)", "O(n^2)", "O(1)"], answer: "O(log n)"),
McqQuestion(domain: "Coding", question: "Which loop checks condition after executing the body?", options: ["for", "while", "do-while", "foreach"], answer: "do-while"),
McqQuestion(domain: "Coding", question: "What is the default value of boolean in Java?", options: ["true", "false", "0", "1"], answer: "false"),
McqQuestion(domain: "Coding", question: "Which keyword is used to inherit a class in Java?", options: ["inherit", "extends", "implements", "super"], answer: "extends"),
McqQuestion(domain: "Coding", question: "Which function is used to get length of a string in Python?", options: ["length()", "strlen()", "len()", "count()"], answer: "len()"),
McqQuestion(domain: "Coding", question: "Which data structure is best for priority tasks?", options: ["Stack", "Queue", "Priority Queue", "Array"], answer: "Priority Queue"),
McqQuestion(domain: "Coding", question: "Which of the following is immutable in Python?", options: ["list", "dict", "set", "tuple"], answer: "tuple"),
McqQuestion(domain: "Coding", question: "Which sorting algorithm is best in worst-case?", options: ["Bubble", "Quick", "Merge", "Selection"], answer: "Merge"),
McqQuestion(domain: "Coding", question: "Which language is used for Android development?", options: ["Swift", "Kotlin", "C#", "JavaScript"], answer: "Kotlin"),
McqQuestion(domain: "Coding", question: "What does IDE stand for?", options: ["Intelligent Debugging Environment", "Integrated Development Environment", "Internal Design Editor", "Interactive Data Executor"], answer: "Integrated Development Environment"),
McqQuestion(domain: "Coding", question: "Which method is called automatically in a class?", options: ["start()", "main()", "constructor", "init()"], answer: "constructor"),
McqQuestion(domain: "Coding", question: "Which keyword is used to stop a loop?", options: ["stop", "exit", "end", "break"], answer: "break"),
McqQuestion(domain: "Coding", question: "Which function is used to read input in C?", options: ["scanf()", "cin", "input()", "get()"], answer: "scanf()"),
McqQuestion(domain: "Coding", question: "Which data structure is used in BFS?", options: ["Stack", "Queue", "Array", "Graph"], answer: "Queue"),
McqQuestion(domain: "Coding", question: "Which algorithm is used for shortest path in graphs?", options: ["Kruskal", "Dijkstra", "DFS", "Merge Sort"], answer: "Dijkstra"),
McqQuestion(domain: "Coding", question: "Which data structure is used for implementing function calls?", options: ["Heap", "Stack", "Queue", "Tree"], answer: "Stack"),
McqQuestion(domain: "Coding", question: "Which symbol is used for comments in Python?", options: ["//", "#", "<!-- -->", "/* */"], answer: "#"),
McqQuestion(domain: "Coding", question: "What is the size of int in C (typically)?", options: ["2 bytes", "4 bytes", "1 byte", "8 bytes"], answer: "4 bytes"),
McqQuestion(domain: "Coding", question: "Which keyword is used to define constant in C?", options: ["final", "define", "const", "static"], answer: "const"),
McqQuestion(domain: "Coding", question: "Which of the following is not a search algorithm?", options: ["Binary Search", "Linear Search", "Bubble Sort", "Interpolation Search"], answer: "Bubble Sort"),
McqQuestion(domain: "Coding", question: "Which traversal visits root-left-right?", options: ["Inorder", "Preorder", "Postorder", "Level order"], answer: "Preorder"),
McqQuestion(domain: "Coding", question: "Which keyword is used to handle exceptions in Java?", options: ["error", "try", "except", "throw"], answer: "try"),
McqQuestion(domain: "Coding", question: "Which structure uses key-value pair?", options: ["Array", "Stack", "HashMap", "Queue"], answer: "HashMap"),
McqQuestion(domain: "Coding", question: "Which keyword creates a thread in Java?", options: ["thread", "implements Runnable", "startThread", "initThread"], answer: "implements Runnable"),
McqQuestion(domain: "Coding", question: "Which protocol is used for web?", options: ["FTP", "HTTP", "SMTP", "POP3"], answer: "HTTP"),
McqQuestion(domain: "Coding", question: "Which symbol is used for OR in C?", options: ["&&", "||", "!", "&"], answer: "||"),
McqQuestion(domain: "Coding", question: "Which algorithm uses divide-and-conquer?", options: ["Merge Sort", "Bubble Sort", "Linear Search", "Selection Sort"], answer: "Merge Sort"),
McqQuestion(domain: "Coding", question: "Which data type stores true/false?", options: ["int", "char", "boolean", "float"], answer: "boolean"),
McqQuestion(domain: "Coding", question: "Which class is parent of all classes in Java?", options: ["Object", "Base", "Main", "Core"], answer: "Object"),
McqQuestion(domain: "Coding", question: "Which of these is not an OOP concept?", options: ["Encapsulation", "Abstraction", "Compilation", "Polymorphism"], answer: "Compilation"),
McqQuestion(domain: "Coding", question: "What does SQL stand for?", options: ["Structured Query Language", "Sequential Question Language", "Simple Query Logic", "System Query Level"], answer: "Structured Query Language"),
McqQuestion(domain: "Coding", question: "Which command is used to create a table in SQL?", options: ["MAKE", "INSERT", "CREATE", "BUILD"], answer: "CREATE"),
McqQuestion(domain: "Coding", question: "Which language is best for AI/ML?", options: ["C", "Java", "Python", "PHP"], answer: "Python"),
McqQuestion(domain: "Coding", question: "Which keyword is used to return value from a function?", options: ["output", "return", "pass", "result"], answer: "return"),
McqQuestion(domain: "Coding", question: "Which of the following is an interpreted language?", options: ["C", "C++", "Python", "Java"], answer: "Python"),
McqQuestion(domain: "Coding", question: "Which of the following is a relational DBMS?", options: ["MySQL", "MongoDB", "Firebase", "Neo4j"], answer: "MySQL"),
McqQuestion(domain: "Coding", question: "What is the output of 2 ** 3 in Python?", options: ["6", "8", "9", "5"], answer: "8"),
McqQuestion(domain: "Coding", question: "Which of the following is a compiled language?", options: ["Python", "JavaScript", "C", "Ruby"], answer: "C"),

  // ⚙ TECHNICAL (5)
 McqQuestion(domain: "Technical", question: "What is the full form of CPU?", options: ["Central Process Unit", "Control Processing Unit", "Central Processing Unit", "Computer Power Unit"], answer: "Central Processing Unit"),
McqQuestion(domain: "Technical", question: "Which language is used to create Android apps?", options: ["Java", "C", "Python", "Swift"], answer: "Java"),
McqQuestion(domain: "Technical", question: "Which component stores data permanently?", options: ["RAM", "ROM", "Cache", "Register"], answer: "ROM"),
McqQuestion(domain: "Technical", question: "Which protocol is used for secure data transfer?", options: ["HTTP", "FTP", "SSH", "SMTP"], answer: "SSH"),
McqQuestion(domain: "Technical", question: "Which material is a conductor?", options: ["Plastic", "Glass", "Copper", "Rubber"], answer: "Copper"),
McqQuestion(domain: "Technical", question: "What is tensile strength?", options: ["Bending strength", "Pulling strength", "Cutting resistance", "Shear strength"], answer: "Pulling strength"),
McqQuestion(domain: "Technical", question: "Which OS is developed by Microsoft?", options: ["Linux", "macOS", "Windows", "Android"], answer: "Windows"),
McqQuestion(domain: "Technical", question: "In DBMS, what is a primary key?", options: ["Unique identifier", "Foreign key", "Duplicate value", "Null value"], answer: "Unique identifier"),
McqQuestion(domain: "Technical", question: "Which component rotates in a motor?", options: ["Stator", "Rotor", "Core", "Brush"], answer: "Rotor"),
McqQuestion(domain: "Technical", question: "Which welding method uses electrodes?", options: ["Gas welding", "Arc welding", "Laser welding", "Friction welding"], answer: "Arc welding"),
McqQuestion(domain: "Technical", question: "What is the unit of electrical resistance?", options: ["Ohm", "Volt", "Ampere", "Watt"], answer: "Ohm"),
McqQuestion(domain: "Technical", question: "Which device converts AC to DC?", options: ["Rectifier", "Inverter", "Amplifier", "Transformer"], answer: "Rectifier"),
McqQuestion(domain: "Technical", question: "Which language is used for AI?", options: ["Python", "HTML", "PHP", "CSS"], answer: "Python"),
McqQuestion(domain: "Technical", question: "AutoCAD is used in?", options: ["Electrical", "Civil", "Medical", "Chemistry"], answer: "Civil"),
McqQuestion(domain: "Technical", question: "Which fluid is used in hydraulics?", options: ["Gas", "Oil", "Water", "Steam"], answer: "Oil"),
McqQuestion(domain: "Technical", question: "Which law explains current, voltage, and resistance?", options: ["Newton’s law", "Ohm’s law", "Faraday’s law", "Hooke’s law"], answer: "Ohm’s law"),
McqQuestion(domain: "Technical", question: "Which is the base unit of temperature?", options: ["Kelvin", "Celsius", "Fahrenheit", "Rankine"], answer: "Kelvin"),
McqQuestion(domain: "Technical", question: "Which tool measures voltage?", options: ["Voltmeter", "Ammeter", "Wattmeter", "Thermometer"], answer: "Voltmeter"),
McqQuestion(domain: "Technical", question: "Which gate has one input and one output?", options: ["NOT", "AND", "OR", "NAND"], answer: "NOT"),
McqQuestion(domain: "Technical", question: "Which machine part reduces friction?", options: ["Bolt", "Nut", "Bearing", "Washer"], answer: "Bearing"),
McqQuestion(domain: "Technical", question: "Unit of power?", options: ["Watt", "Ohm", "Joule", "Volt"], answer: "Watt"),
McqQuestion(domain: "Technical", question: "Which software is used for coding?", options: ["MS Word", "Excel", "VS Code", "Photoshop"], answer: "VS Code"),
McqQuestion(domain: "Technical", question: "What is the function of a compiler?", options: ["Executes code", "Translates code", "Writes code", "Deletes code"], answer: "Translates code"),
McqQuestion(domain: "Technical", question: "Which sensor detects temperature?", options: ["LDR", "Thermistor", "Ultrasonic", "Proximity"], answer: "Thermistor"),
McqQuestion(domain: "Technical", question: "Which force opposes motion?", options: ["Gravity", "Friction", "Centripetal", "Torque"], answer: "Friction"),
McqQuestion(domain: "Technical", question: "Which circuit allows current in one direction?", options: ["AC", "DC", "Open", "Closed"], answer: "DC"),
McqQuestion(domain: "Technical", question: "Which is a renewable source?", options: ["Coal", "Petrol", "Wind", "Gas"], answer: "Wind"),
McqQuestion(domain: "Technical", question: "What is an algorithm?", options: ["Program", "Set of rules", "Command", "Loop"], answer: "Set of rules"),
McqQuestion(domain: "Technical", question: "Which engine is used in bikes?", options: ["IC engine", "EC engine", "Hydraulic", "Nuclear"], answer: "IC engine"),
McqQuestion(domain: "Technical", question: "Which programming language is object-oriented?", options: ["C", "Assembly", "Python", "HTML"], answer: "Python"),
McqQuestion(domain: "Technical", question: "Which unit is used for frequency?", options: ["Watt", "Ohm", "Hertz", "Joule"], answer: "Hertz"),
McqQuestion(domain: "Technical", question: "Which civil structure holds water?", options: ["Bridge", "Dam", "Wall", "Road"], answer: "Dam"),
McqQuestion(domain: "Technical", question: "Which network has the longest range?", options: ["LAN", "PAN", "MAN", "WAN"], answer: "WAN"),
McqQuestion(domain: "Technical", question: "Which of the following is an IDE?", options: ["Photoshop", "Notepad", "Eclipse", "Chrome"], answer: "Eclipse"),
McqQuestion(domain: "Technical", question: "Which IC is used in logic circuits?", options: ["7805", "555", "7400", "LM317"], answer: "7400"),
McqQuestion(domain: "Technical", question: "Which machine tool removes metal?", options: ["Lathe", "Milling", "Drill", "All of these"], answer: "All of these"),
McqQuestion(domain: "Technical", question: "Which is a ferrous metal?", options: ["Copper", "Aluminium", "Cast Iron", "Bronze"], answer: "Cast Iron"),
McqQuestion(domain: "Technical", question: "Which software is used in mechanical design?", options: ["Tally", "SolidWorks", "CorelDraw", "SAP"], answer: "SolidWorks"),
McqQuestion(domain: "Technical", question: "Which component controls current flow?", options: ["Capacitor", "Resistor", "Transformer", "Switch"], answer: "Switch"),
McqQuestion(domain: "Technical", question: "What is torque?", options: ["Rotational force", "Speed", "Weight", "Pressure"], answer: "Rotational force"),
McqQuestion(domain: "Technical", question: "Which protocol is used in emails?", options: ["FTP", "SMTP", "HTTP", "IP"], answer: "SMTP"),
McqQuestion(domain: "Technical", question: "Which language is compiled?", options: ["Python", "HTML", "Java", "CSS"], answer: "Java"),
McqQuestion(domain: "Technical", question: "Which bridge type uses cables?", options: ["Beam", "Arch", "Suspension", "Truss"], answer: "Suspension"),
McqQuestion(domain: "Technical", question: "What is fluid mechanics?", options: ["Study of solids", "Study of liquids & gases", "Study of metals", "Study of circuits"], answer: "Study of liquids & gases"),
McqQuestion(domain: "Technical", question: "Which is a primary color in printing?", options: ["Red", "Green", "Cyan", "Yellow"], answer: "Cyan"),
McqQuestion(domain: "Technical", question: "Which command shows IP details?", options: ["ping", "ipconfig", "mkdir", "ls"], answer: "ipconfig"),
McqQuestion(domain: "Technical", question: "Which device boosts signal?", options: ["Repeater", "Modem", "Router", "Switch"], answer: "Repeater"),

McqQuestion(domain: "OS", question: "What is the primary function of an operating system?", options: ["Manage hardware and software resources", "Compile code", "Edit documents", "Browse the internet"], answer: "Manage hardware and software resources"),
McqQuestion(domain: "OS", question: "Which of the following is not an operating system?", options: ["Windows", "Linux", "Oracle", "macOS"], answer: "Oracle"),
McqQuestion(domain: "OS", question: "Which operating system is open source?", options: ["Windows", "Linux", "macOS", "DOS"], answer: "Linux"),
McqQuestion(domain: "OS", question: "Which of the following is not a function of an OS?", options: ["Memory management", "Process scheduling", "Application development", "File system management"], answer: "Application development"),
McqQuestion(domain: "OS", question: "What is a kernel?", options: ["A software that manages the computer’s resources", "A computer virus", "A type of storage device", "A hardware chip"], answer: "A software that manages the computer’s resources"),
McqQuestion(domain: "OS", question: "Which of the following is an example of a real-time operating system?", options: ["RTOS", "MS-DOS", "UNIX", "Windows XP"], answer: "RTOS"),
McqQuestion(domain: "OS", question: "What does 'multitasking' mean in OS?", options: ["Executing multiple programs simultaneously", "Connecting multiple computers", "Deleting multiple files", "Installing multiple applications"], answer: "Executing multiple programs simultaneously"),
McqQuestion(domain: "OS", question: "Which part of the OS handles file operations?", options: ["File system", "Scheduler", "Memory manager", "I/O controller"], answer: "File system"),
McqQuestion(domain: "OS", question: "Which of the following OS is used in mobile phones?", options: ["Android", "Linux", "macOS", "Windows 10"], answer: "Android"),
McqQuestion(domain: "OS", question: "Which system call is used to create a new process in Unix?", options: ["fork()", "exec()", "init()", "spawn()"], answer: "fork()"),
McqQuestion(domain: "OS", question: "What is a deadlock?", options: ["A situation where processes wait indefinitely for resources", "A file system error", "A virus", "A hardware failure"], answer: "A situation where processes wait indefinitely for resources"),
McqQuestion(domain: "OS", question: "Which memory is directly accessible by the CPU?", options: ["Main memory", "Hard disk", "Cache", "CD-ROM"], answer: "Main memory"),
McqQuestion(domain: "OS", question: "Which scheduling algorithm gives each process a fixed time slot?", options: ["Round Robin", "FIFO", "Shortest Job First", "Priority Scheduling"], answer: "Round Robin"),
McqQuestion(domain: "OS", question: "Which OS runs on servers?", options: ["Windows Server", "iOS", "Android", "Symbian"], answer: "Windows Server"),
McqQuestion(domain: "OS", question: "Which layer interacts directly with the hardware?", options: ["Kernel", "Shell", "Application", "System Library"], answer: "Kernel"),
McqQuestion(domain: "OS", question: "Which of the following is not a state of process?", options: ["Running", "Waiting", "Ready", "Loading"], answer: "Loading"),
McqQuestion(domain: "OS", question: "In which memory allocation strategy is the largest available block chosen?", options: ["Worst Fit", "Best Fit", "First Fit", "Next Fit"], answer: "Worst Fit"),
McqQuestion(domain: "OS", question: "What is virtual memory?", options: ["Memory on the hard drive used as RAM", "Read-only memory", "Cache memory", "Non-volatile memory"], answer: "Memory on the hard drive used as RAM"),
McqQuestion(domain: "OS", question: "Which command is used to list processes in Unix?", options: ["ps", "ls", "pwd", "kill"], answer: "ps"),
McqQuestion(domain: "OS", question: "Which type of OS is used in embedded systems?", options: ["Real-time OS", "Batch OS", "Network OS", "Multitasking OS"], answer: "Real-time OS"),
McqQuestion(domain: "OS", question: "Which is not a page replacement algorithm?", options: ["FIFO", "LRU", "Optimal", "Shortest Job First"], answer: "Shortest Job First"),
McqQuestion(domain: "OS", question: "What does the acronym 'IPC' stand for?", options: ["Inter Process Communication", "Internal Processor Check", "Internet Protocol Control", "Input Processing Circuit"], answer: "Inter Process Communication"),
McqQuestion(domain: "OS", question: "Which of these is not a type of scheduler?", options: ["Long-term", "Mid-term", "Short-term", "End-term"], answer: "End-term"),
McqQuestion(domain: "OS", question: "Which system call is used to terminate a process?", options: ["exit()", "kill()", "terminate()", "end()"], answer: "exit()"),
McqQuestion(domain: "OS", question: "What is thrashing in OS?", options: ["Excessive paging", "Heavy CPU load", "Multiple interrupts", "Multiple logins"], answer: "Excessive paging"),
McqQuestion(domain: "OS", question: "Which of the following is a type of user interface?", options: ["GUI", "CLI", "TUI", "All of the above"], answer: "All of the above"),
McqQuestion(domain: "OS", question: "What is the purpose of device drivers?", options: ["To interface hardware with OS", "To store data", "To run software", "To secure the OS"], answer: "To interface hardware with OS"),
McqQuestion(domain: "OS", question: "Which one is not a component of an operating system?", options: ["Compiler", "Scheduler", "File System", "Memory Manager"], answer: "Compiler"),
McqQuestion(domain: "OS", question: "Which of the following is an example of a network OS?", options: ["Windows Server", "Android", "MS-DOS", "iOS"], answer: "Windows Server"),
McqQuestion(domain: "OS", question: "Which memory is non-volatile?", options: ["ROM", "RAM", "Cache", "Registers"], answer: "ROM"),
  // 💻 SQL (5)
 McqQuestion(domain: "SQL", question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Language", "Structured Quick Language", "Sequential Query Language"], answer: "Structured Query Language"),
McqQuestion(domain: "SQL", question: "Which SQL statement is used to retrieve data?", options: ["GET", "SELECT", "FETCH", "PULL"], answer: "SELECT"),
McqQuestion(domain: "SQL", question: "Which clause is used to filter records?", options: ["WHERE", "HAVING", "ORDER BY", "GROUP BY"], answer: "WHERE"),
McqQuestion(domain: "SQL", question: "Which function returns the number of rows?", options: ["COUNT()", "SUM()", "AVG()", "TOTAL()"], answer: "COUNT()"),
McqQuestion(domain: "SQL", question: "What is a primary key?", options: ["Foreign key", "Unique identifier", "Duplicate key", "Null key"], answer: "Unique identifier"),
McqQuestion(domain: "SQL", question: "Which keyword is used to sort data?", options: ["GROUP BY", "ORDER BY", "SORT", "RANK"], answer: "ORDER BY"),
McqQuestion(domain: "SQL", question: "Which SQL command adds new rows?", options: ["ADD", "INSERT", "APPEND", "CREATE"], answer: "INSERT"),
McqQuestion(domain: "SQL", question: "Which command removes a table?", options: ["REMOVE", "DELETE", "DROP", "CLEAR"], answer: "DROP"),
McqQuestion(domain: "SQL", question: "Which SQL clause groups records?", options: ["GROUP BY", "SORT BY", "AGGREGATE", "BUNDLE"], answer: "GROUP BY"),
McqQuestion(domain: "SQL", question: "What is a foreign key?", options: ["Duplicate key", "Reference to another table", "Primary key", "Null value"], answer: "Reference to another table"),
McqQuestion(domain: "SQL", question: "What does NULL mean in SQL?", options: ["0", "Blank string", "Missing value", "Zero value"], answer: "Missing value"),
McqQuestion(domain: "SQL", question: "Which SQL keyword prevents duplicates?", options: ["DISTINCT", "UNIQUE", "PRIMARY", "DIFFERENT"], answer: "DISTINCT"),
McqQuestion(domain: "SQL", question: "Which operator is used for pattern matching?", options: ["LIKE", "MATCH", "FIND", "PATTERN"], answer: "LIKE"),
McqQuestion(domain: "SQL", question: "Which wildcard matches one character?", options: ["_", "%", "*", "#"], answer: "_"),
McqQuestion(domain: "SQL", question: "Which wildcard matches zero or more characters?", options: ["%", "_", "*", "@"], answer: "%"),
McqQuestion(domain: "SQL", question: "Which command is used to update rows?", options: ["CHANGE", "MODIFY", "UPDATE", "ALTER"], answer: "UPDATE"),
McqQuestion(domain: "SQL", question: "Which SQL function finds average?", options: ["MEAN()", "AVG()", "TOTAL()", "SUM()"], answer: "AVG()"),
McqQuestion(domain: "SQL", question: "Which keyword combines rows from two tables?", options: ["MERGE", "COMBINE", "JOIN", "ATTACH"], answer: "JOIN"),
McqQuestion(domain: "SQL", question: "Which JOIN returns all records from both tables?", options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL JOIN"], answer: "FULL JOIN"),
McqQuestion(domain: "SQL", question: "What does the HAVING clause filter?", options: ["Rows", "Groups", "Tables", "Columns"], answer: "Groups"),
McqQuestion(domain: "SQL", question: "Which clause is used after GROUP BY?", options: ["WHERE", "ORDER BY", "HAVING", "SORT BY"], answer: "HAVING"),
McqQuestion(domain: "SQL", question: "Which command removes rows from a table?", options: ["DELETE", "DROP", "REMOVE", "TRUNCATE"], answer: "DELETE"),
McqQuestion(domain: "SQL", question: "What does the ALTER command do?", options: ["Change table structure", "Insert rows", "Delete table", "Drop column"], answer: "Change table structure"),
McqQuestion(domain: "SQL", question: "Which SQL type allows only whole numbers?", options: ["VARCHAR", "DATE", "INT", "CHAR"], answer: "INT"),
McqQuestion(domain: "SQL", question: "Which data type stores large text?", options: ["VARCHAR", "INT", "TEXT", "CHAR"], answer: "TEXT"),
McqQuestion(domain: "SQL", question: "Which command creates a table?", options: ["INSERT", "DEFINE", "CREATE", "MAKE"], answer: "CREATE"),
McqQuestion(domain: "SQL", question: "Which keyword is used to rename a column?", options: ["CHANGE", "MODIFY", "AS", "RENAME"], answer: "AS"),
McqQuestion(domain: "SQL", question: "Which function gives maximum value?", options: ["TOP()", "LARGEST()", "MAX()", "BIGGEST()"], answer: "MAX()"),
McqQuestion(domain: "SQL", question: "What is the result of INNER JOIN?", options: ["Only matching records", "All records", "Null records", "Random records"], answer: "Only matching records"),
McqQuestion(domain: "SQL", question: "Which constraint ensures value is entered?", options: ["UNIQUE", "DEFAULT", "NOT NULL", "KEY"], answer: "NOT NULL"),
McqQuestion(domain: "SQL", question: "Which constraint avoids duplicate values?", options: ["UNIQUE", "PRIMARY", "CHECK", "NOT NULL"], answer: "UNIQUE"),
McqQuestion(domain: "SQL", question: "What is a view?", options: ["Permanent table", "Stored procedure", "Virtual table", "Raw table"], answer: "Virtual table"),
McqQuestion(domain: "SQL", question: "Which keyword is used in subqueries?", options: ["IN", "OUT", "SET", "GO"], answer: "IN"),
McqQuestion(domain: "SQL", question: "Which command resets auto-increment ID?", options: ["RESTART", "TRUNCATE", "RESET", "CLEAR"], answer: "TRUNCATE"),
McqQuestion(domain: "SQL", question: "Which command is used to remove duplicates?", options: ["FILTER", "REMOVE", "DISTINCT", "ELIMINATE"], answer: "DISTINCT"),
McqQuestion(domain: "SQL", question: "What does SQL injection affect?", options: ["Application speed", "Database security", "Network", "Disk space"], answer: "Database security"),
McqQuestion(domain: "SQL", question: "Which function finds minimum value?", options: ["SMALL()", "MIN()", "LOW()", "LEAST()"], answer: "MIN()"),
McqQuestion(domain: "SQL", question: "Which clause limits returned rows?", options: ["LIMIT", "COUNT", "STOP", "TOP"], answer: "LIMIT"),
McqQuestion(domain: "SQL", question: "Which function adds up numeric values?", options: ["AVG()", "MAX()", "SUM()", "COUNT()"], answer: "SUM()"),
McqQuestion(domain: "SQL", question: "Which JOIN includes non-matching left table rows?", options: ["INNER", "LEFT JOIN", "RIGHT JOIN", "FULL JOIN"], answer: "LEFT JOIN"),
McqQuestion(domain: "SQL", question: "Which SQL keyword creates a database?", options: ["INSERT", "CREATE", "NEW", "MAKE"], answer: "CREATE"),
McqQuestion(domain: "SQL", question: "Which statement changes table name?", options: ["RENAME TO", "UPDATE TABLE", "CHANGE NAME", "MODIFY"], answer: "RENAME TO"),
McqQuestion(domain: "SQL", question: "Which constraint checks a condition?", options: ["CHECK", "WHERE", "IF", "RESTRICT"], answer: "CHECK"),
McqQuestion(domain: "SQL", question: "Which function returns current date?", options: ["NOW()", "DATE()", "CURRENT_DATE()", "SYSDATE()"], answer: "CURRENT_DATE()"),
McqQuestion(domain: "SQL", question: "Which clause removes rows based on condition?", options: ["DROP", "DELETE", "REMOVE", "ELIMINATE"], answer: "DELETE"),
McqQuestion(domain: "SQL", question: "Which function counts NULLs?", options: ["COUNT(*)", "COUNT(ALL)", "COUNT(column)", "None of these"], answer: "None of these"),
McqQuestion(domain: "SQL", question: "Which JOIN retrieves common data?", options: ["OUTER JOIN", "INNER JOIN", "LEFT JOIN", "CROSS JOIN"], answer: "INNER JOIN"),
McqQuestion(domain: "SQL", question: "Which data type stores dates?", options: ["CHAR", "DATETIME", "INT", "FLOAT"], answer: "DATETIME"),
McqQuestion(domain: "SQL", question: "What is normalization?", options: ["Removing duplicates", "Organizing data", "Backing up data", "Joining tables"], answer: "Organizing data"),
McqQuestion(domain: "SQL", question: "Which command rolls back a transaction?", options: ["ROLLBACK", "UNDO", "CANCEL", "STOP"], answer: "ROLLBACK"),

  // 🗃 DBMS (5)
  McqQuestion(domain: "DBMS", question: "What does SQL stand for?", options: ["Structured Query Language", "Simple Query Language", "Set Query Logic", "None"], answer: "Structured Query Language"),
McqQuestion(domain: "DBMS", question: "Primary key is?", options: ["Unique identifier", "Duplicate", "Null", "Table"], answer: "Unique identifier"),
McqQuestion(domain: "DBMS", question: "Which normal form removes multivalued dependency?", options: ["1NF", "2NF", "4NF", "3NF"], answer: "4NF"),
McqQuestion(domain: "DBMS", question: "ACID stands for?", options: ["Atomicity, Consistency, Isolation, Durability", "Accuracy, Control, Integrity, Design", "None", "Set rules"], answer: "Atomicity, Consistency, Isolation, Durability"),
McqQuestion(domain: "DBMS", question: "Command to remove table?", options: ["DELETE", "DROP", "REMOVE", "ERASE"], answer: "DROP"),
McqQuestion(domain: "DBMS", question: "Which command is used to remove all records from a table?", options: ["DELETE", "TRUNCATE", "REMOVE", "ERASE"], answer: "TRUNCATE"),
McqQuestion(domain: "DBMS", question: "Foreign key is used to?", options: ["Maintain referential integrity", "Remove rows", "Sort table", "None"], answer: "Maintain referential integrity"),
McqQuestion(domain: "DBMS", question: "What is a view?", options: ["Virtual table", "Physical table", "Temporary table", "Key"], answer: "Virtual table"),
McqQuestion(domain: "DBMS", question: "Which command is used to change data in a table?", options: ["UPDATE", "ALTER", "MODIFY", "SELECT"], answer: "UPDATE"),
McqQuestion(domain: "DBMS", question: "What is a candidate key?", options: ["Unique key", "Primary key", "Foreign key", "Composite key"], answer: "Unique key"),
McqQuestion(domain: "DBMS", question: "What does DDL stand for?", options: ["Data Definition Language", "Data Dynamic Language", "Database Design Language", "None"], answer: "Data Definition Language"),
McqQuestion(domain: "DBMS", question: "Which is not a DDL command?", options: ["CREATE", "DROP", "UPDATE", "ALTER"], answer: "UPDATE"),
McqQuestion(domain: "DBMS", question: "Which command is used to add a new column?", options: ["ADD", "APPEND", "INSERT", "MODIFY"], answer: "ADD"),
McqQuestion(domain: "DBMS", question: "Which is not a type of join?", options: ["Inner Join", "Outer Join", "Top Join", "Cross Join"], answer: "Top Join"),
McqQuestion(domain: "DBMS", question: "Which normal form eliminates transitive dependency?", options: ["1NF", "2NF", "3NF", "BCNF"], answer: "3NF"),
McqQuestion(domain: "DBMS", question: "What is a transaction?", options: ["Set of SQL operations", "A trigger", "View", "Schema"], answer: "Set of SQL operations"),
McqQuestion(domain: "DBMS", question: "What is normalization?", options: ["Organizing data", "Deleting tables", "Designing schema", "Creating users"], answer: "Organizing data"),
McqQuestion(domain: "DBMS", question: "Which clause is used for filtering rows?", options: ["WHERE", "FROM", "GROUP BY", "ORDER BY"], answer: "WHERE"),
McqQuestion(domain: "DBMS", question: "Which function returns the number of rows?", options: ["COUNT()", "SUM()", "AVG()", "MAX()"], answer: "COUNT()"),
McqQuestion(domain: "DBMS", question: "Which key allows null values?", options: ["Foreign key", "Primary key", "Candidate key", "Super key"], answer: "Foreign key"),
McqQuestion(domain: "DBMS", question: "Which isolation level is the strictest?", options: ["Serializable", "Read Committed", "Read Uncommitted", "Repeatable Read"], answer: "Serializable"),
McqQuestion(domain: "DBMS", question: "What is a trigger?", options: ["Automatic execution", "Manual execution", "View", "Table"], answer: "Automatic execution"),
McqQuestion(domain: "DBMS", question: "Which SQL clause groups records?", options: ["GROUP BY", "ORDER BY", "HAVING", "WHERE"], answer: "GROUP BY"),
McqQuestion(domain: "DBMS", question: "Which function returns the highest value?", options: ["MAX()", "SUM()", "COUNT()", "AVG()"], answer: "MAX()"),
McqQuestion(domain: "DBMS", question: "Which operator is used to compare NULL?", options: ["IS NULL", "= NULL", "== NULL", "EQUAL NULL"], answer: "IS NULL"),
McqQuestion(domain: "DBMS", question: "Which SQL keyword is used to sort?", options: ["ORDER BY", "SORT BY", "GROUP BY", "SELECT"], answer: "ORDER BY"),
McqQuestion(domain: "DBMS", question: "What is the output of SELECT 2 + NULL?", options: ["NULL", "2", "Error", "0"], answer: "NULL"),
McqQuestion(domain: "DBMS", question: "Which of the following is not a constraint?", options: ["CHECK", "DEFAULT", "INDEX", "NOT NULL"], answer: "INDEX"),
McqQuestion(domain: "DBMS", question: "Which language is used to query DB?", options: ["SQL", "HTML", "CSS", "PHP"], answer: "SQL"),
McqQuestion(domain: "DBMS", question: "Which clause filters grouped records?", options: ["HAVING", "WHERE", "ORDER BY", "SELECT"], answer: "HAVING"),
McqQuestion(domain: "DBMS", question: "To remove duplicates in SELECT?", options: ["DISTINCT", "UNIQUE", "SEPARATE", "REMOVE"], answer: "DISTINCT"),
McqQuestion(domain: "DBMS", question: "Which clause defines sorting order?", options: ["ORDER BY", "SORT", "GROUP", "HAVING"], answer: "ORDER BY"),
McqQuestion(domain: "DBMS", question: "What is a composite key?", options: ["Multiple columns", "One column", "Foreign key", "None"], answer: "Multiple columns"),
McqQuestion(domain: "DBMS", question: "What does TCL stand for?", options: ["Transaction Control Language", "Table Control Language", "Temporary Column Language", "None"], answer: "Transaction Control Language"),
McqQuestion(domain: "DBMS", question: "ROLLBACK is used to?", options: ["Undo transaction", "Create table", "Alter column", "Drop database"], answer: "Undo transaction"),
McqQuestion(domain: "DBMS", question: "What is the default sorting order?", options: ["Ascending", "Descending", "Random", "None"], answer: "Ascending"),
McqQuestion(domain: "DBMS", question: "Which symbol denotes pattern in LIKE?", options: ["%", "#", "@", "*"], answer: "%"),
McqQuestion(domain: "DBMS", question: "Which data type is used for text?", options: ["VARCHAR", "INT", "FLOAT", "BOOLEAN"], answer: "VARCHAR"),
McqQuestion(domain: "DBMS", question: "Which SQL keyword is used to modify structure?", options: ["ALTER", "UPDATE", "MODIFY", "INSERT"], answer: "ALTER"),
McqQuestion(domain: "DBMS", question: "What does SELECT * do?", options: ["Selects all columns", "Selects primary key", "Deletes records", "Shows schema"], answer: "Selects all columns"),
McqQuestion(domain: "DBMS", question: "How to rename a column?", options: ["ALTER TABLE ... RENAME COLUMN", "UPDATE COLUMN", "RENAME COLUMN ONLY", "MODIFY NAME"], answer: "ALTER TABLE ... RENAME COLUMN"),
McqQuestion(domain: "DBMS", question: "Which command removes only data, not structure?", options: ["TRUNCATE", "DROP", "DELETE", "ERASE"], answer: "DELETE"),
McqQuestion(domain: "DBMS", question: "Which clause limits output rows?", options: ["LIMIT", "GROUP BY", "TOP", "RESTRICT"], answer: "LIMIT"),
McqQuestion(domain: "DBMS", question: "Which one is not part of ACID?", options: ["Atomicity", "Clarity", "Durability", "Isolation"], answer: "Clarity"),
McqQuestion(domain: "DBMS", question: "Which SQL command adds records?", options: ["INSERT", "ADD", "APPEND", "NEW"], answer: "INSERT"),
McqQuestion(domain: "DBMS", question: "Which function returns average?", options: ["AVG()", "SUM()", "MEAN()", "TOTAL()"], answer: "AVG()"),
McqQuestion(domain: "DBMS", question: "Which constraint checks a condition?", options: ["CHECK", "DEFAULT", "FOREIGN", "UNIQUE"], answer: "CHECK"),
McqQuestion(domain: "DBMS", question: "Which of the following is a DML command?", options: ["INSERT", "CREATE", "DROP", "ALTER"], answer: "INSERT"),
McqQuestion(domain: "DBMS", question: "Which clause is optional in SELECT?", options: ["WHERE", "FROM", "SELECT", "TABLE"], answer: "WHERE"),
McqQuestion(domain: "DBMS", question: "What is the result of CROSS JOIN?", options: ["Cartesian product", "No result", "Single row", "Sorted list"], answer: "Cartesian product"),

  // 🌐 NETWORKING (5)
McqQuestion(domain: "Networking", question: "IP address is how many bits?", options: ["16", "32", "64", "128"], answer: "32"),
McqQuestion(domain: "Networking", question: "HTTP works on which layer?", options: ["Transport", "Application", "Network", "Data Link"], answer: "Application"),
McqQuestion(domain: "Networking", question: "Which protocol is connection-oriented?", options: ["UDP", "TCP", "IP", "ICMP"], answer: "TCP"),
McqQuestion(domain: "Networking", question: "DNS is used for?", options: ["Email", "Naming websites", "Streaming", "Uploading"], answer: "Naming websites"),
McqQuestion(domain: "Networking", question: "Switch works on which layer?", options: ["Data Link", "Network", "Transport", "Application"], answer: "Data Link"),
McqQuestion(domain: "Networking", question: "Which topology has a central hub?", options: ["Star", "Ring", "Bus", "Mesh"], answer: "Star"),
McqQuestion(domain: "Networking", question: "Which device connects different networks?", options: ["Router", "Switch", "Hub", "Repeater"], answer: "Router"),
McqQuestion(domain: "Networking", question: "What does TCP stand for?", options: ["Transmission Control Protocol", "Transfer Control Protocol", "Transport Communication Protocol", "None"], answer: "Transmission Control Protocol"),
McqQuestion(domain: "Networking", question: "Which protocol is used to transfer files?", options: ["FTP", "HTTP", "SMTP", "IMAP"], answer: "FTP"),
McqQuestion(domain: "Networking", question: "Which device works on physical layer?", options: ["Hub", "Switch", "Router", "Bridge"], answer: "Hub"),
McqQuestion(domain: "Networking", question: "Default port of HTTP?", options: ["21", "23", "80", "25"], answer: "80"),
McqQuestion(domain: "Networking", question: "Which layer handles routing?", options: ["Network", "Transport", "Data Link", "Application"], answer: "Network"),
McqQuestion(domain: "Networking", question: "Which protocol uses three-way handshake?", options: ["TCP", "UDP", "FTP", "HTTP"], answer: "TCP"),
McqQuestion(domain: "Networking", question: "Which is a private IP range?", options: ["192.168.x.x", "8.8.8.8", "1.1.1.1", "172.0.0.1"], answer: "192.168.x.x"),
McqQuestion(domain: "Networking", question: "IPv6 address size?", options: ["32-bit", "64-bit", "128-bit", "256-bit"], answer: "128-bit"),
McqQuestion(domain: "Networking", question: "OSI model has how many layers?", options: ["5", "6", "7", "8"], answer: "7"),
McqQuestion(domain: "Networking", question: "MAC address is?", options: ["Physical address", "IP address", "Logical address", "Port number"], answer: "Physical address"),
McqQuestion(domain: "Networking", question: "Which protocol is used for email sending?", options: ["SMTP", "FTP", "POP3", "IMAP"], answer: "SMTP"),
McqQuestion(domain: "Networking", question: "Which protocol is used for secure communication?", options: ["HTTPS", "HTTP", "FTP", "TELNET"], answer: "HTTPS"),
McqQuestion(domain: "Networking", question: "Which layer handles encryption?", options: ["Presentation", "Application", "Network", "Physical"], answer: "Presentation"),
McqQuestion(domain: "Networking", question: "IPSec is used in?", options: ["VPN", "HTTP", "DNS", "SMTP"], answer: "VPN"),
McqQuestion(domain: "Networking", question: "ARP stands for?", options: ["Address Resolution Protocol", "Advanced Routing Protocol", "Address Relay Protocol", "None"], answer: "Address Resolution Protocol"),
McqQuestion(domain: "Networking", question: "Which protocol resolves domain names?", options: ["DNS", "ARP", "DHCP", "HTTP"], answer: "DNS"),
McqQuestion(domain: "Networking", question: "Default port of SSH?", options: ["21", "22", "23", "80"], answer: "22"),
McqQuestion(domain: "Networking", question: "Which is a transport layer protocol?", options: ["TCP", "IP", "HTTP", "ICMP"], answer: "TCP"),
McqQuestion(domain: "Networking", question: "Ping uses which protocol?", options: ["ICMP", "TCP", "UDP", "ARP"], answer: "ICMP"),
McqQuestion(domain: "Networking", question: "What is bandwidth?", options: ["Data capacity", "Address", "Error", "Delay"], answer: "Data capacity"),
McqQuestion(domain: "Networking", question: "DHCP is used for?", options: ["Assign IP", "Assign MAC", "Routing", "Encryption"], answer: "Assign IP"),
McqQuestion(domain: "Networking", question: "Which device boosts signal?", options: ["Repeater", "Switch", "Router", "Hub"], answer: "Repeater"),
McqQuestion(domain: "Networking", question: "Which layer segments data?", options: ["Transport", "Network", "Data Link", "Session"], answer: "Transport"),
McqQuestion(domain: "Networking", question: "Which layer in OSI model creates session?", options: ["Session", "Presentation", "Network", "Transport"], answer: "Session"),
McqQuestion(domain: "Networking", question: "Full form of URL?", options: ["Uniform Resource Locator", "Uniform Routing Layer", "Universal Resource Locator", "User Resource Locator"], answer: "Uniform Resource Locator"),
McqQuestion(domain: "Networking", question: "Which protocol is not reliable?", options: ["UDP", "TCP", "FTP", "HTTPS"], answer: "UDP"),
McqQuestion(domain: "Networking", question: "SSL operates at which layer?", options: ["Transport", "Application", "Session", "Presentation"], answer: "Presentation"),
McqQuestion(domain: "Networking", question: "IPv4 uses how many bits?", options: ["32", "64", "128", "256"], answer: "32"),
McqQuestion(domain: "Networking", question: "Which of these is NOT a topology?", options: ["Star", "Ring", "Chain", "Bus"], answer: "Chain"),
McqQuestion(domain: "Networking", question: "Firewall works at which layer?", options: ["Network", "Application", "Data Link", "Transport"], answer: "Network"),
McqQuestion(domain: "Networking", question: "Which one is NOT a valid IP?", options: ["192.300.1.1", "10.0.0.1", "172.16.0.0", "192.168.0.1"], answer: "192.300.1.1"),
McqQuestion(domain: "Networking", question: "Traceroute uses which protocol?", options: ["ICMP", "UDP", "TCP", "FTP"], answer: "ICMP"),
McqQuestion(domain: "Networking", question: "Which is used for media access control?", options: ["MAC", "IP", "ARP", "DHCP"], answer: "MAC"),
McqQuestion(domain: "Networking", question: "Data link layer is responsible for?", options: ["Framing", "Routing", "Encryption", "Segmentation"], answer: "Framing"),
McqQuestion(domain: "Networking", question: "Which one is NOT a switching type?", options: ["Circuit", "Message", "Packet", "Frame"], answer: "Frame"),
McqQuestion(domain: "Networking", question: "Which protocol handles errors?", options: ["TCP", "UDP", "FTP", "IP"], answer: "TCP"),
McqQuestion(domain: "Networking", question: "Which of these is a Layer 3 device?", options: ["Router", "Switch", "Hub", "Bridge"], answer: "Router"),
McqQuestion(domain: "Networking", question: "Which one provides IP-to-MAC mapping?", options: ["ARP", "DNS", "DHCP", "ICMP"], answer: "ARP"),
McqQuestion(domain: "Networking", question: "Packet switching is used in?", options: ["Internet", "Telephone", "Fax", "Cable TV"], answer: "Internet"),
McqQuestion(domain: "Networking", question: "What does NAT stand for?", options: ["Network Address Translation", "Name Allocation Table", "Network Access Tool", "None"], answer: "Network Address Translation"),
McqQuestion(domain: "Networking", question: "What is jitter?", options: ["Delay variation", "Bandwidth", "Noise", "Packet loss"], answer: "Delay variation"),
McqQuestion(domain: "Networking", question: "What is port number of HTTPS?", options: ["80", "443", "21", "22"], answer: "443"),
McqQuestion(domain: "Networking", question: "Which protocol is used for streaming?", options: ["RTP", "SMTP", "SSH", "DNS"], answer: "RTP"),
McqQuestion(domain: "Networking", question: "Which of these is a broadband tech?", options: ["DSL", "LAN", "WAN", "Wi-Fi"], answer: "DSL"),
McqQuestion(domain: "Networking", question: "Which of the following is a protocol analyzer?", options: ["Wireshark", "Chrome", "Outlook", "Word"], answer: "Wireshark"),

];

class McqQuestion {
  final String domain;
  final String question;
  final List<String> options;
  final String answer;

  McqQuestion({
    required this.domain,
    required this.question,
    required this.options,
    required this.answer,
  });
}